[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ['nanposweb']

[project]
name = "nanposweb"
description = ""
requires-python= ">=3.9"
license = {text = "MIT"}
version = "0.16.0"

[project.optional-dependencies]
dev = ['flake8']