[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "nanposweb"
description = ""
requires-python= ">=3.9"
license = {text = "MIT"}
version = "0.16.0"

dependencies = ['Flask', 'Flask-SQLAlchemy', 'Flask-Login', 'Flask-WTF', 'Flask-Principal', 'gunicorn',
    'psycopg2-binary']

[project.optional-dependencies]
dev = ['flake8']