[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ['nanposweb']

[project]
name = "nanposweb"
description = ""
requires-python= ">=3.9"
license = {text = "MIT"}
version = "1.1.2"
dependencies = [
	"Flask==2.2.3",
	"Flask-SQLAlchemy",
	"Flask-Login",
	"Flask-WTF",
	"Flask-Principal",
	"psycopg2-binary",
	"werkzeug==2.2.3",
]

[project.optional-dependencies]
dev = ['flake8']

[tool.flake8]
max-line-length = 120
exclude = [
    # No need to traverse our git directory
    ".git",
    # There's no value in checking cache directories
    "__pycache__",
	# Build directories
	"build/*"
]