name: Python linting
on: [push, pull_request]
jobs:
  check_linting:
    name: Check Python linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Display Python version
        run: python --version
      - name: Install linting package
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Run linting
        run: flake8 --count --show-source --statistics --max-line-length=120